# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190512_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='git',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='heroku',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
